version: "3"
services:
  website:
    container_name: website
    build: .
    restart: always
    ports:
      - "80"
    depends_on: 
      - letsencrypt

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=CHANGETOEMAIL+letsencrypt@gmail.com
      - URL=gikken.com
      - SUBDOMAINS=www,api
      - VALIDATION=http
      - TZ=Europe/London
      - PUID=0
      - PGID=0
    restart: unless-stopped
